[project]
name = "cqlib"
description = "A high-performance quantum computing SDK with a Rust core and Python bindings."
requires-python = ">=3.10"
license = "Apache-2.0"
readme = "README.md"
authors = [
    { name = "Cqlib Development Team", email = "tianyan@chinatelecom.cn" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
]
keywords = [
    "cqlib",
    "quantum circuit",
    "quantum computing",
    "quantum programming language",
    "quantum",
    "sdk",
]

dependencies = ["numpy>=2.1.0"]
dynamic = ["version"]

[dependency-groups]
test = ["pytest>=8.0", "resvg-py==0.5.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = ["--strict-markers"]

[project.urls]
Homepage = "https://qc.zdxlz.com/"
Documentation = "https://qc.zdxlz.com/learn/#/resource/informationSpace?lang=zh&cId=/mkdocs/zh/cqlib/01-overview.html"
Repository = "https://gitee.com/cq-lib/cqlib"
Issues = "https://gitee.com/cq-lib/cqlib/issues"


[build-system]
requires = ["maturin>=1.10,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "cqlib._native"
include-python-files = ["cqlib/**", ]
include = [{ path = "cqlib/py.typed", format = ["sdist", "wheel"] }]
exclude = [
    "cqlib/**/*.so",
    "cqlib/**/*.dylib",
    "cqlib/**/*.dll",
    "cqlib/**/__pycache__",
    "cqlib/**/*.pyc",
]
sdist-include = ["Cargo.toml", "Cargo.lock", "src/**/*", "cqlib/**/*"]
